# Generated by Django 4.1 on 2023-12-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_selectlogs_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="location",
            field=models.CharField(default="默认地点", max_length=20, verbose_name="上课地点"),
        ),
    ]
