# Generated by Django 4.1 on 2023-12-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_projects_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="time",
            field=models.CharField(
                default="早八早八！统统给我上早八！！！！", max_length=20, verbose_name="上课地点"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="location",
            field=models.CharField(
                default="宿舍宿舍 必须在宿舍上课！", max_length=20, verbose_name="上课地点"
            ),
        ),
    ]
