# Generated by Django 4.1 on 2023-12-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_projects_time_alter_projects_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="time",
            field=models.CharField(
                default="早八早八！统统给我上早八！！！！", max_length=20, verbose_name="上课时间"
            ),
        ),
        migrations.CreateModel(
            name="TestLocation",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=13,
                        primary_key=True,
                        serialize=False,
                        verbose_name="记录编号",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="宿舍宿舍 必须在宿舍考试！", max_length=20, verbose_name="考试地点"
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        default="早八早八！统统给我早八考试！！！！", max_length=20, verbose_name="考试时间"
                    ),
                ),
                (
                    "workPaln",
                    models.ForeignKey(
                        db_column="plan_id",
                        max_length=13,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.workpalns",
                    ),
                ),
            ],
            options={
                "db_table": "testlocation",
            },
        ),
    ]
